package com.ddas.backend.model;

// ============================================================
// FileData.java  —  Package: com.ddas.backend.model
// ------------------------------------------------------------
// PURPOSE:
//   JPA Entity that maps to the "file_data" table in the H2 database.
//   Each row represents ONE uploaded file, including its metadata
//   and raw binary content (stored as a BLOB).
//
// DATABASE TABLE:  file_data
//
// COLUMNS:
//   id           BIGINT        Primary key, auto-incremented
//   file_name    VARCHAR       Display name of the file
//   file_hash    VARCHAR(64)   SHA-256 hash (unique per file — used for duplicate detection)
//   uploaded_by  VARCHAR       Email of the user who uploaded the file
//   file_size    BIGINT        File size in bytes
//   created_at   TIMESTAMP     Date/time of upload (server-side)
//   file_content BLOB          Raw binary content of the file
//
// USED BY:
//   FileRepository  → queries/saves FileData objects
//   FileService     → builds FileData before saving; reads it for download/view
//   FileController  → returns FileData list as JSON to the frontend
// ============================================================

import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.Id;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Column;
import java.time.LocalDateTime;

@Entity                       // Marks this class as a JPA-managed database entity
@Table(name = "file_data")    // Maps to the "file_data" table in H2
public class FileData {

    // ── Primary Key ──────────────────────────────────────────────
    // Auto-generated by the database (1, 2, 3, ...)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // ── File Metadata ────────────────────────────────────────────

    // The file's display name (e.g. "report.pdf")
    @Column(nullable = false)
    private String fileName;

    // SHA-256 hex digest of the file — UNIQUE constraint ensures
    // the same file cannot be uploaded twice (duplicate detection)
    @Column(unique = true, nullable = false, length = 64)
    private String fileHash;

    // Email address of the user who uploaded the file
    @Column
    private String uploadedBy;

    // File size in bytes (used for display on the dashboard)
    @Column
    private Long fileSize;

    // Server-side timestamp when the file was uploaded
    @Column
    private LocalDateTime createdAt;

    // ── File Content (BLOB) ──────────────────────────────────────
    // The actual binary content of the uploaded file.
    // Stored as a BLOB in H2 so files can be downloaded later.
    // NOTE: Large files will increase database size significantly.
    @jakarta.persistence.Lob
    @Column(name = "file_content", columnDefinition = "BLOB")
    private byte[] fileContent;


    // ── Getters & Setters ────────────────────────────────────────
    // Standard Java bean accessors — required by JPA and Spring

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getFileHash() {
        return fileHash;
    }

    public void setFileHash(String fileHash) {
        this.fileHash = fileHash;
    }

    public String getUploadedBy() {
        return uploadedBy;
    }

    public void setUploadedBy(String uploadedBy) {
        this.uploadedBy = uploadedBy;
    }

    public Long getFileSize() {
        return fileSize;
    }

    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public byte[] getFileContent() {
        return fileContent;
    }

    public void setFileContent(byte[] fileContent) {
        this.fileContent = fileContent;
    }
}