package com.ddas.backend.model;

// ============================================================
// User.java  —  Package: com.ddas.backend.model
// ------------------------------------------------------------
// PURPOSE:
//   JPA Entity that maps to the "users" table in the H2 database.
//   Each row represents ONE registered user account.
//
// DATABASE TABLE:  users
//
// COLUMNS:
//   id        BIGINT    Primary key, auto-incremented
//   email     VARCHAR   User's email address (UNIQUE — no duplicates allowed)
//   password  VARCHAR   BCrypt-hashed password (NEVER stored as plain text)
//
// SECURITY NOTE:
//   Passwords are hashed using BCryptPasswordEncoder in AuthService
//   before being stored here. The raw password is never saved.
//
// USED BY:
//   UserRepository  → queries/saves User objects
//   AuthService     → finds users by email, saves new users, updates passwords
// ============================================================

import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.Id;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Column;

@Entity                  // Marks this class as a JPA-managed database entity
@Table(name = "users")   // Maps to the "users" table in H2
public class User {

    // ── Primary Key ──────────────────────────────────────────────
    // Auto-generated by the database (1, 2, 3, ...)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // ── User Fields ──────────────────────────────────────────────

    // Email is the unique identifier for each account.
    // The UNIQUE constraint prevents two users from sharing an email.
    @Column(unique = true, nullable = false)
    private String email;

    // BCrypt-hashed password. Never store raw passwords.
    // Example stored value: "$2a$10$N9qo8uLOickgx..."
    @Column(nullable = false)
    private String password;


    // ── Constructors ─────────────────────────────────────────────

    // No-arg constructor required by JPA
    public User() {
    }

    // Convenience constructor used in AuthService.register()
    public User(String email, String password) {
        this.email = email;
        this.password = password;  // password must already be BCrypt-encoded!
    }


    // ── Getters & Setters ────────────────────────────────────────
    // Standard Java bean accessors — required by JPA and Spring

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;  // Always pass an already-encoded password!
    }
}
